### ISSUE TITLE
Your README is erroring?

### ISSUE THREAD

**Issue by chcokr** [wooorm/mdast#84]
When I run mdast 2.0.0 on your `readme.md`, I get the following error:

```
~/code/mdast $ mdast readme.md

readme.md
        1:1  error    Error: mdast-util-definitions expected node
    at gather (/Users/chcokr/code/mdast/node_modules/mdast-util-definitions/index.js:53:15)
    at getDefinitionFactory (/Users/chcokr/code/mdast/node_modules/mdast-util-definitions/index.js:85:26)
    at gatherReferences (/Users/chcokr/code/mdast/node_modules/mdast-validate-links/index.js:127:21)
    at Of.transformer (/Users/chcokr/code/mdast/node_modules/mdast-validate-links/index.js:474:26)
    at Of.<anonymous> (/usr/local/lib/node_modules/mdast/node_modules/wrap-fn/index.js:75:16)
    at Of.<anonymous> (/usr/local/lib/node_modules/mdast/node_modules/wrap-fn/index.js:57:27)
    at next (/usr/local/lib/node_modules/mdast/node_modules/ware/lib/index.js:85:20)
    at /usr/local/lib/node_modules/mdast/node_modules/wrap-fn/index.js:121:18
    at Of.<anonymous> (/usr/local/lib/node_modules/mdast/node_modules/wrap-fn/index.js:83:42)
    at Of.<anonymous> (/usr/local/lib/node_modules/mdast/node_modules/wrap-fn/index.js:57:27)

✖ 1 error
```

Just trying to jump onto #60 :smile:

**Comment by wooorm** [comment]
Maybe remove all node_modules and install again? That often fixes it :)

**Comment by chcokr** [comment]
Ah, there you go. What can `rm -rf` not solve?!

**Comment by wooorm** [comment]
:wink:
