### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by dikmax** [wooorm/mdast#89]
Trying to include mdast-lint into workflow, but mdast crashes on start 

```
$ node_modules/.bin/mdast
/Users/dikmax/workspace/dikmax.name-shake/node_modules/mdast/node_modules/npm-prefix/node_modules/untildify/index.js:7
                throw new TypeError('Expected a string');
                ^

TypeError: Expected a string
    at module.exports (/Users/dikmax/workspace/dikmax.name-shake/node_modules/mdast/node_modules/npm-prefix/node_modules/untildify/index.js:7:9)
    at module.exports (/Users/dikmax/workspace/dikmax.name-shake/node_modules/mdast/node_modules/npm-prefix/index.js:10:10)
    at Object.<anonymous> (/Users/dikmax/workspace/dikmax.name-shake/node_modules/mdast/lib/cli/file-pipeline/configure.js:20:38)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/dikmax/workspace/dikmax.name-shake/node_modules/mdast/lib/cli/file-pipeline/index.js:19:17)
```

**Comment by wooorm** [comment]
Could you post some code? Just an error is pretty hard to work with for me...

**Comment by eush77** [comment]
I'm sorry! Could you reinstall dependencies and check again? (Just bumped npm-prefix to 1.1.1.)

**Comment by wooorm** [comment]
@eush77 this seems to be happening in [npm-prefix](https://github.com/eush77/npm-prefix/blob/2afb5f93b541ac864272bf73a1e6968319ebb3b2/index.js#L13), which probably passes a non-string `prefix` variable.

**Comment by wooorm** [comment]
Oh nice, thanks @eush77 ;)

**Comment by dikmax** [comment]
Updated dependencies fixed issue! Thanx!

**Comment by wooorm** [comment]
Thanks for the work @eush77, thanks for reporting @dikmax!
